### ISSUE TITLE
sparse_dot_topn_for_blocks dependency broken with in Cython version

### ISSUE THREAD

**Issue by alexiskaldany** [Bergvca/string_grouper#93]
error when install string-grouper
generated by `sparse_dot_topn_for_blocks` dependency
` ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  /tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/dist.py:509: InformationOnly: Normalizing '0.3.1-3' to '0.3.1.post3'
    self.metadata.version = self._normalize_version(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-310
  creating build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  copying sparse_dot_topn_for_blocks/awesome_cossim_topn.py -> build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  copying sparse_dot_topn_for_blocks/__init__.py -> build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  running egg_info
  writing sparse_dot_topn_for_blocks.egg-info/PKG-INFO
  writing dependency_links to sparse_dot_topn_for_blocks.egg-info/dependency_links.txt
  writing requirements to sparse_dot_topn_for_blocks.egg-info/requires.txt
  writing top-level names to sparse_dot_topn_for_blocks.egg-info/top_level.txt
  reading manifest file 'sparse_dot_topn_for_blocks.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'LICENSE'
  writing manifest file 'sparse_dot_topn_for_blocks.egg-info/SOURCES.txt'
  copying sparse_dot_topn_for_blocks/array_wrappers.pxd -> build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  copying sparse_dot_topn_for_blocks/array_wrappers.pyx -> build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  copying sparse_dot_topn_for_blocks/sparse_dot_topn.pyx -> build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  copying sparse_dot_topn_for_blocks/sparse_dot_topn_parallel.cpp -> build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  copying sparse_dot_topn_for_blocks/sparse_dot_topn_parallel.h -> build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  copying sparse_dot_topn_for_blocks/sparse_dot_topn_source.cpp -> build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  copying sparse_dot_topn_for_blocks/sparse_dot_topn_source.h -> build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  copying sparse_dot_topn_for_blocks/sparse_dot_topn_threaded.pyx -> build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  running build_ext
  /tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/tmpaqn4vovk/sparse_dot_topn_for_blocks-0.3.1.post3/sparse_dot_topn_for_blocks/array_wrappers.pxd
    tree = Parsing.p_module(s, pxd, full_module_name)
  Compiling ./sparse_dot_topn_for_blocks/array_wrappers.pyx because it changed.
  [1/1] Cythonizing ./sparse_dot_topn_for_blocks/array_wrappers.pyx
  building 'sparse_dot_topn_for_blocks.array_wrappers' extension
  creating build/temp.linux-x86_64-cpython-310
  creating build/temp.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/tmpx4q1lfox/.venv/include -I/usr/local/include/python3.10 -I/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/numpy/core/include -c ./sparse_dot_topn_for_blocks/array_wrappers.cpp -o build/temp.linux-x86_64-cpython-310/./sparse_dot_topn_for_blocks/array_wrappers.o -std=c++0x -pthread -O3
  g++ -shared build/temp.linux-x86_64-cpython-310/./sparse_dot_topn_for_blocks/array_wrappers.o -L/usr/local/lib -o build/lib.linux-x86_64-cpython-310/sparse_dot_topn_for_blocks/array_wrappers.cpython-310-x86_64-linux-gnu.so
  /tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/tmpaqn4vovk/sparse_dot_topn_for_blocks-0.3.1.post3/sparse_dot_topn_for_blocks/sparse_dot_topn.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  # April 14, 2021
  
  # distutils: language = c++
  
  from libcpp.vector cimport vector
  from array_wrappers cimport ArrayWrapper_int, ArrayWrapper_float, ArrayWrapper_double
  ^
  ------------------------------------------------------------
  
  sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:23:0: 'array_wrappers.pxd' not found
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  # April 14, 2021
  
  # distutils: language = c++
  
  from libcpp.vector cimport vector
  from array_wrappers cimport ArrayWrapper_int, ArrayWrapper_float, ArrayWrapper_double
  ^
  ------------------------------------------------------------
  
  sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:23:0: 'array_wrappers/ArrayWrapper_int.pxd' not found
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  # April 14, 2021
  
  # distutils: language = c++
  
  from libcpp.vector cimport vector
  from array_wrappers cimport ArrayWrapper_int, ArrayWrapper_float, ArrayWrapper_double
  ^
  ------------------------------------------------------------
  
  sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:23:0: 'array_wrappers/ArrayWrapper_float.pxd' not found
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  # April 14, 2021
  
  # distutils: language = c++
  
  from libcpp.vector cimport vector
  from array_wrappers cimport ArrayWrapper_int, ArrayWrapper_float, ArrayWrapper_double
  ^
  ------------------------------------------------------------
  
  sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:23:0: 'array_wrappers/ArrayWrapper_double.pxd' not found
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  	) except +;
  
  cpdef ArrayWrapper_template(vector[float_ft] vCx):
  	# raise Exception("In sparse_dot_topn.pyx")
  	if float_ft is float:
  		return ArrayWrapper_float(vCx)
           ^
  ------------------------------------------------------------
  
  sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:116:9: 'ArrayWrapper_float' is not a constant, variable or function identifier
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  cpdef ArrayWrapper_template(vector[float_ft] vCx):
  	# raise Exception("In sparse_dot_topn.pyx")
  	if float_ft is float:
  		return ArrayWrapper_float(vCx)
  	elif float_ft is double:
  		return ArrayWrapper_double(vCx)
           ^
  ------------------------------------------------------------
  
  sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:118:9: 'ArrayWrapper_double' is not a constant, variable or function identifier
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  
  	if nnz_max_is_too_small:
  		
  		# raise Exception("In sparse_dot_topn.pyx")
  		
  		c_indices = np.asarray(ArrayWrapper_int(vCj)).squeeze(axis=0)
                           ^
  ------------------------------------------------------------
  
  sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:209:25: 'ArrayWrapper_int' is not a constant, variable or function identifier
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  
  	if nnz_max_is_too_small:
  		
  		# raise Exception("In sparse_dot_topn.pyx")
  		
  		c_indices = np.asarray(ArrayWrapper_int(vCj)).squeeze(axis=0)
                           ^
  ------------------------------------------------------------
  
  sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:209:25: 'ArrayWrapper_int' is not a constant, variable or function identifier
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  	
  	if nnz_max_is_too_small:
  		
  		# raise Exception("In sparse_dot_topn.pyx")
  		
  		c_indices = np.asarray(ArrayWrapper_int(vCj)).squeeze(axis=0)
                           ^
  ------------------------------------------------------------
  
  sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:296:25: 'ArrayWrapper_int' is not a constant, variable or function identifier
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
  	
  	if nnz_max_is_too_small:
  		
  		# raise Exception("In sparse_dot_topn.pyx")
  		
  		c_indices = np.asarray(ArrayWrapper_int(vCj)).squeeze(axis=0)
                           ^
  ------------------------------------------------------------
  
  sparse_dot_topn_for_blocks/sparse_dot_topn.pyx:296:25: 'ArrayWrapper_int' is not a constant, variable or function identifier
  Compiling ./sparse_dot_topn_for_blocks/sparse_dot_topn.pyx because it changed.
  [1/1] Cythonizing ./sparse_dot_topn_for_blocks/sparse_dot_topn.pyx
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 65, in <module>
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
      self.build_extensions()
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
      new_ext = cythonize(
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
      cythonize_one(*args)
    File "/tmp/tmpx4q1lfox/.venv/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
      raise CompileError(None, pyx_file)
  Cython.Compiler.Errors.CompileError: ./sparse_dot_topn_for_blocks/sparse_dot_topn.pyx
  

  at /usr/local/lib/python3.10/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with sparse-dot-topn-for-blocks (0.3.1.post3) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "sparse-dot-topn-for-blocks (==0.3.1.post3)"'.`

**Comment by MahireAsadzade** [comment]
I face the same issue as well

**Comment by varun-affinsys** [comment]
This error is coming while installing string_grouper==0.6.1, in python 3.9

**Comment by ethanfan19** [comment]
Same issue here with python 3.9.13 and latest numpy, scipy packges

**Comment by jdh208** [comment]
Same issue here with Python 3.11.4, NumPy 1.25.1, SciPy 1.11.1

**Comment by kykyi** [comment]
Unsure if the maintainers of `sparse_dot_topn_for_blocks` are still on the project, this PR has been open for 2 weeks 😞: https://github.com/ParticularMiner/sparse_dot_topn_for_blocks/pull/4

**Comment by AlejandroUPC** [comment]
@kykyi  Is this repo also inactive, or? Also affected by this

**Comment by kykyi** [comment]
I think it is both inactive and affected by this @AlejandroUPC 😞

**Comment by GuillaumePressiat** [comment]
@ParticularMiner did a nice job with blocks splitting for matrix multiplication time and memory optimization (sparse_dot_topn_for_blocks, topn). 
But for now these packages are not maintained anymore...

For what I've seen, chunk/block splitting is now integrated into sparse_dot_topn since [v1](https://github.com/ing-bank/sparse_dot_topn/tree/master?tab=readme-ov-file#distributing-the-top-n-multiplication-of-two-large-o10m-sparse-matrices-over-a-cluster).

https://github.com/GuillaumePressiat/string_grouper/releases

From string grouper 0.5.0 @Bergvca version (i.e. without 0.6.0 and sparse_dot_topn_for_blocks and topn c++ dependencies which are not  maintained anymore) I've updated dependencies and string_grouper code to take these new feature of ing-bank/sparse_dot_topn into account and specific api changes since v1.

A proposal release "0.7.0.3" of string_grouper from my repo is now available for testing if needed.

I think it's a fix for this issue: 
- since sparse_dot_topn_for_blocks depends of old numpy api and cython versions, it's breaked
- it seems difficult and time consuming to update specifically this package just for string_grouper 
- for me it's better to rely on ing-bank/sparse_dot_topn main branch

**Comment by GuillaumePressiat** [comment]
Hi @Bergvca,

Thanks for your answer. And also thanks for making this package available!

> That is awesome! what is the best way to integrate this into string_grouper? I haven't had a lot of time to maintain it, but this seems like a good solution to get it up to date again.

The release 0.7.0.3 from my repo already "works". To integrate it into your repo if this is what you're asking for, I can take a little more time to work on my side on a clean sheet, do some tests to propose a pull request in a branch for a "0.7.0" version?

It can also be an occasion to build some minimal documentation for users (material-mkdocs for instance)? 
With this doc exposed, it will be easier to assess if the api is more or less stable and consistent towards 0.6.2 one? 

I'm not completely familiar with the code history and when I say "it works", for the moment it means it works for me but I've done a choice of restarting from 0.5.0 to get it up working quickly.

**Comment by Bergvca** [comment]
Hi @GuillaumePressiat,

> The release 0.7.0.3 from my repo already "works". To integrate it into your repo if this is what you're asking for, I can take a little more time to work on my side on a clean sheet, do some tests to propose a pull request in a branch for a "0.7.0" version?

Right, this would be awesome. It sounds like a good way to get this repo back to working with the latest versions of Cython / numpy. 

Adding documentation and extra functionality is always welcome :)

**Comment by GuillaumePressiat** [comment]
Hi @Bergvca,

About that, a candidate for release 0.7.0 is now available here:
https://github.com/GuillaumePressiat/string_grouper/tree/from_0.6_to_0.7
The tests are ok.

For documentation it's quickly done here with material-mkdocs. Work in progress:
https://guillaumepressiat.github.io/string_grouper/

If it's ok for you I will redirect this into your repo via a pull request?
If needed we can also exchange by mail for details.

**Comment by GuillaumePressiat** [comment]
Thanks @Bergvca,

See here : https://github.com/Bergvca/string_grouper/pull/99

**Comment by Bergvca** [comment]
Hi @GuillaumePressiat, 

Many thanks! I've tested the code and it looks good so far, however the last update from @ParticularMiner (i guess the v0.6) contained some performance improvements that made the library extremely fast. 

For comparison, i ran the old version on my laptop and the `sec__edgar_company_info.csv file`, and it took around 8 minutes to calculate all matches. In the new version this is 36 minutes with the default settings. It ran in 31 minutes when using `tfidf_matrix_dtype = np.float32`.

I did not compare the quality of the output yet. Assuming that the quality is pretty much the same, a big drop in performance would be a shame imo (even though I fully support the idea of being based on a library that is maintained and easy to install). 

Is there a way we can somehow re-introduce those improvements?

**Comment by GuillaumePressiat** [comment]
Hi @Bergvca,

I've not seen a regression like this on my side, maybe more an improvement (firstly because sparse_dot_topn is faster than before).

Can you share me the code you run please ?

I believe this is just related to the n_blocks argument which I'm not setting automatically as it was in 0.6. For the moment I took it to None by default. 
Setting n_blocks = (1,180) for instance will really speed up things.
But maybe I'm wrong.

## With n_blocks set

<img width="963" alt="image" src="https://github.com/user-attachments/assets/1b38ff91-028b-4cd5-bdad-ef8b44591f8e" />

## Without n_blocks

<img width="954" alt="image" src="https://github.com/user-attachments/assets/4650a0ec-2a08-4788-9382-b0e817ee2c4d" />

I'm on a mac with 10 CPUs but there is a huge difference between the two and almost thirty minutes without n_blocks.

For tfidf_matrix_dtype = np.float32 setting I get your point but the difference is not here for the big part.

Can you share me the code you run please or try with n_blocks too on your side ?

**Comment by GuillaumePressiat** [comment]
Hi @Bergvca,

Moving backward to this issue https://github.com/Bergvca/string_grouper/pull/74, it seems that 8e4 is not optimal at least for me on my 2024 laptop, 4e3 is really better meaning around (1, 170) as the number of blocks. and not (1,8) as guessed by @particularMiner in 0.6.2 version (right block size was fixed to 80 000 so n_blocks to 8 for 663 000 rows). But in the readme it's also showned that 200 is a good size for right n_blocks which means 663 000 / 200 = 3300 and not 80 000? I think he guessed 80 000 as an optimal value when left block is not fixed to 1.

In your discussion I see you linked it to cpu cache size and that it depends on computer specs.
You says:

> "Yes that makes sense - the CPU sees large arrays so puts it in RAM. If it sees a small array it just puts it in Cache directly, or something like that?"

@ParticularMiner said:

> "So what are the optimum block number values for any given Series? That is anyone's guess, and may likely depend on the data itself. Furthermore, as hinted above, the answer may vary from computer to computer.
> 
> We however encourage the user to make judicious use of the n_blocks parameter to boost performance of string_grouper whenever possible."
> 

Below somes tests on my computer with sec_edgar_company csv and different settings:

<img width="1328" alt="Image" src="https://github.com/user-attachments/assets/5d5daeed-6832-41d5-9132-33d0aebafaaf" />

<img width="1327" alt="Image" src="https://github.com/user-attachments/assets/c8c7bd74-8754-4c79-8afd-c51ee2509761" />

<img width="1327" alt="Image" src="https://github.com/user-attachments/assets/f5171509-5949-4f1a-b670-3ba393d86eab" />

<img width="1330" alt="Image" src="https://github.com/user-attachments/assets/6e39b1f6-2cc1-417e-a17d-3afcc6040fe0" />

From what I've observed when left block size is 1 I propose to set a value to obtain around 4000 for right block size if it's not set in function call? That's where I obtain best performance results.
**I have updated my pull request to take this into account and set n_blocks automatically based on data size** as it was, just tuned it.
Let me know if it speed up things on your side!
Many thanks

Otherwise it means that performances are really platform dependant and I find it's tricky to mask this parameter as it can change user wait time significantly... 

Many thanks

**Comment by Bergvca** [comment]
Hi @GuillaumePressiat,

Indeed using your `n_blocks = (1,180)` setting sped the process up to 7 min 30, so even faster than the v0.6 version. Agreed that having a sensible default (even if it might not be the optimum for everyone) is better than not setting it at all. 

I tested the your latest version, and it runs in **6 min 19**, so it seems like a very sensible default, at least for this dataset :)

For my side i'm ready to merge and create a new version in pypi, if that is ok with you?

**Comment by GuillaumePressiat** [comment]
Hi @Bergvca,

Many thanks to have test it again.. 
Ok for pypi. Let me know if I you can help for something.

After that I could take more time on documentation, visible [here](https://guillaumepressiat.github.io/string_grouper/) for the moment but that will be easier to follow if it's hosted in this repo instead I think?
 
I may take some time to post an article on my blog to present an application of this package to join different datasets in hospital healthcare context (patient names with typos in two different datasets) or find patients with duplicates ids in one database.

**Comment by Bergvca** [comment]
Hmm, i'm trying to merge but not able to resolve the conflicts. Is that something you can do from your side?

**Comment by GuillaumePressiat** [comment]
Ok
I've done something... 
It's seems ok now?

And I also added lines in CHANGELOG

**Comment by GuillaumePressiat** [comment]
By the way
One way to initialize the docs into your repo is shown [here](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-mkdocs)
And with github actions to automate it there is a tip [here](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions)

**Comment by Bergvca** [comment]
Merged and uploaded to pypi! 

This package can now be installed with a simple `pip install string-grouper` again!

**Comment by GuillaumePressiat** [comment]
Many thanks @Bergvca!

N.B.: on pypi we have inherited of my semantic version number "0.7.0.7" instead of 0.7.0. The fourth digit was for pre-release versions I have incremented. It's a minor detail (0.7.0 or better 0.7.1 will fix this)

**Comment by GuillaumePressiat** [comment]
Hi @Bergvca,

- for documentation, do you think it will be feasible on your side?
- also for 0.7.1 instead of 0.7.0.7? It's a minor thing but I could put a pull request if you prefer
- there is a lot of old issues that stay oppened, maybe it will be good to close them? For the ones related to sparse_dot_topn_for_blocks I added a comment that propose to try the 0.7 version

Thanks!

**Comment by Bergvca** [comment]
Hi @GuillaumePressiat,

* For the documentation - yes, in fact its already uploaded, I just haven't added a link to it yet. I was thinking to move a lot that is currently in the readme.md to the documentation so that we have a cleaner landing page
* For the version, no worries, ill handle it
* Yes, let me close some of them now :)

**Comment by Bergvca** [comment]
This is done! 

Thanks again for the awesome work @GuillaumePressiat!

I will close the issue :)
